name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [
          ubuntu-22.04, 
          # macos-13, 
          # macos-14, 
          # windows-2022
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: buzznode
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Python Dependencies
        shell: bash
        run: |
          pip install grpcio-tools nanopb protobuf

      - name: Initialize West and Update Manifest
        working-directory: buzznode
        shell: bash
        run: |
          west init -l .
          west config manifest.project-filter -- +nanopb
          west update

      - name: Setup Zephyr SDK
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: buzznode
          toolchains: "arm-zephyr-eabi:riscv64-zephyr-elf:x86_64-zephyr-elf:xtensa-esp-elf:mips-zephyr-elf:sparc-zephyr-elf:arc-zephyr-elf:aarch64-zephyr-elf"

      - name: Build firmware
        working-directory: buzznode
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            EXTRA_TWISTER_FLAGS="--short-build-path -O/tmp/twister-out"
          fi
          west twister -T app -v --inline-logs --integration $EXTRA_TWISTER_FLAGS

      - name: Twister Tests
        working-directory: buzznode
        shell: bash
        run: |
          if [ "${{ runner.os }}" = "Windows" ]; then
            EXTRA_TWISTER_FLAGS="--short-build-path -O/tmp/twister-out"
          fi
          west twister -T tests -v --inline-logs --integration $EXTRA_TWISTER_FLAGS
